'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cat_Empresa
    Public Property id As Decimal
    Public Property nombre_comercial As String
    Public Property razon_social As String
    Public Property direccion As String
    Public Property colonia As String
    Public Property ciudad As String
    Public Property estado As String
    Public Property codigo_postal As String
    Public Property rfc As String
    Public Property telefono1 As String
    Public Property telefono2 As String
    Public Property pagina As String
    Public Property email As String
    Public Property firma1 As String
    Public Property firma2 As String
    Public Property logo As Byte()
    Public Property inactivo As Nullable(Of Boolean)

End Class
