'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class InventarioSoftDB
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=InventarioSoftDB")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Cat_Empresa() As DbSet(Of Cat_Empresa)
    Public Property Cat_aseguradora() As DbSet(Of Cat_aseguradora)
    Public Property Cat_Familia() As DbSet(Of Cat_Familia)
    Public Property Cat_Imagenes() As DbSet(Of Cat_Imagenes)
    Public Property Cat_Marca() As DbSet(Of Cat_Marca)
    Public Property Cat_Movimientos() As DbSet(Of Cat_Movimientos)
    Public Property Cat_Tipo() As DbSet(Of Cat_Tipo)
    Public Property Cat_Ubicaciones() As DbSet(Of Cat_Ubicaciones)
    Public Property Sys_Usuarios() As DbSet(Of Sys_Usuarios)
    Public Property Opr_MovInventario() As DbSet(Of Opr_MovInventario)
    Public Property Opr_Productos() As DbSet(Of Opr_Productos)
    Public Property Vw_Opr_Productos() As DbSet(Of Vw_Opr_Productos)

End Class
