'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Opr_MovInventario
    Public Property id As Integer
    Public Property id_producto As Nullable(Of Integer)
    Public Property id_movimiento As Nullable(Of Integer)
    Public Property fecha As Nullable(Of Date)
    Public Property id_operador As Nullable(Of Integer)
    Public Property invt_anterior As Nullable(Of Integer)
    Public Property invt_nuevo As Nullable(Of Integer)
    Public Property comentario As String
    Public Property codigoRecibo As String

End Class
