'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Opr_Productos
    Public Property id_producto As Decimal
    Public Property codigo As String
    Public Property descripcion As String
    Public Property existencia As Nullable(Of Decimal)
    Public Property id_familia As Integer
    Public Property id_marca As Nullable(Of Integer)
    Public Property id_tipo As Nullable(Of Integer)
    Public Property id_aseguradora As Nullable(Of Integer)
    Public Property id_ubicacion As Nullable(Of Integer)
    Public Property modelo As String
    Public Property foto1 As Byte()
    Public Property foto2 As Byte()
    Public Property foto3 As Byte()
    Public Property foto4 As Byte()
    Public Property activo As Nullable(Of Boolean)
    Public Property placa As String
    Public Property num_pieza As String
    Public Property anaquel As String

End Class
